This notebook performs preprocessing on the NYC TLC taxi dataset including missing value handling, datetime correction, feature engineering, negative value removal, and outlier treatment.

LOADING DATASET

In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("NYC_TLC_Messy.csv")
df

,TripID,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6.0,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/17 14:53,04/11/17 15:19,1.0,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1.0,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/17 13:17,05/07/17 13:48,1.0,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,NaN,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22894,47368116,1,06/29/2017 7:30:30 PM,06/29/2017 7:43:29 PM,1.0,0.00,1,N,79,148,3,8.5,1.0,0.5,0.00,0.0,0.3,10.30
22895,84575569,2,10/08/17 02:24,10/08/17 02:59,1.0,16.40,1,N,151,26,2,46.0,0.5,0.5,0.00,0.0,0.3,47.30
22896,98456136,1,11/20/2017 9:59:41 AM,11/20/2017 10:07:39 AM,1.0,0.70,1,N,100,48,2,6.5,0.0,0.5,0.00,0.0,0.3,7.30
22897,36424085,2,04/29/2017 11:05:05 PM,04/29/2017 11:18:14 PM,1.0,2.66,1,N,68,114,1,11.0,0.5,0.5,3.08,0.0,0.3,15.38
22898,15752972,2,02/27/2017 8:24:37 AM,02/27/2017 8:33:42 AM,4.0,1.48,1,N,186,230,1,8.0,0.0,0.5,2.20,0.0,0.3,11.00

In [2]:
df.shape

(22899, 18)

In [3]:
df.columns

Index(['TripID', 'VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount'],
      dtype='object')

In [4]:
df.dtypes

TripID                     int64
VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID                 int64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
dtype: object

In [5]:
df.describe()

,TripID,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,2.289900e+04,22899.000000,22441.000000,22899.000000,22899.000000,22899.000000,22899.000000,22899.000000,22211.000000,22899.000000,22899.000000,22899.000000,22899.000000,22899.000000,22899.000000
mean,5.674302e+07,1.556007,1.637449,3.999734,1.043583,162.460806,161.481811,1.337657,35.509235,0.332918,0.497336,1.833506,0.311276,0.299528,16.301783
std,3.274246e+07,0.496864,1.290482,23.488479,0.706535,66.643210,70.167796,0.496878,473.459519,0.463194,0.040381,2.795209,1.396868,0.016099,16.069215
min,1.212700e+04,1.000000,-2.000000,0.000000,1.000000,1.000000,1.000000,1.000000,-120.000000,-1.000000,-0.500000,0.000000,0.000000,-0.300000,-120.300000
25%,2.853214e+07,1.000000,1.000000,0.990000,1.000000,114.000000,112.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.300000,8.750000
50%,5.671911e+07,2.000000,1.000000,1.610000,1.000000,162.000000,162.000000,1.000000,9.500000,0.000000,0.500000,1.350000,0.000000,0.300000,11.800000
75%,8.533269e+07,2.000000,2.000000,3.100000,1.000000,233.000000,233.000000,2.000000,14.500000,0.500000,0.500000,2.450000,0.000000,0.300000,17.800000
max,1.134863e+08,2.000000,6.000000,500.000000,99.000000,265.000000,265.000000,4.000000,9999.000000,4.500000,0.500000,200.000000,19.100000,0.300000,1200.290000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22899 entries, 0 to 22898
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TripID                 22899 non-null  int64
 1   VendorID               22899 non-null  int64
 2   tpep_pickup_datetime   22899 non-null  object
 3   tpep_dropoff_datetime  22899 non-null  object
 4   passenger_count        22441 non-null  float64
 5   trip_distance          22899 non-null  float64
 6   RatecodeID             22899 non-null  int64
 7   store_and_fwd_flag     22899 non-null  object
 8   PULocationID           22899 non-null  int64
 9   DOLocationID           22899 non-null  int64
 10  payment_type           22899 non-null  int64
 11  fare_amount            22211 non-null  float64
 12  extra                  22899 non-null  float64
 13  mta_tax                22899 non-null  float64
 14  tip_amount             22899 non-null  float64
 15  tolls_amount           22899 non-null  float64
 16  improvement_surcharge  22899 non-null  float64
 17  total_amount           22899 non-null  float64
dtypes: float64(9), int64(6), object(3)
memory usage: 3.1+ MB

Missing Value Handling

In [7]:
df.isnull().sum()

TripID                     0
VendorID                   0
tpep_pickup_datetime       0
tpep_dropoff_datetime      0
passenger_count          458
trip_distance              0
RatecodeID                 0
store_and_fwd_flag         0
PULocationID               0
DOLocationID               0
payment_type               0
fare_amount              688
extra                      0
mta_tax                    0
tip_amount                 0
tolls_amount               0
improvement_surcharge      0
total_amount               0
dtype: int64

In [8]:
df['fare_amount'].fillna(df['fare_amount'].median(), inplace=True)
df['passenger_count'].fillna(df['passenger_count'].median(), inplace=True)

In [9]:
df.isnull().sum()

TripID                   0
VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
dtype: int64

REMOVING DUPLICATES

In [10]:
print("Duplicates:", df.duplicated().sum())
df.drop_duplicates(inplace=True)
print("After removing duplicates:", df.shape)

Duplicates: 192
After removing duplicates: (22707, 18)

In [11]:
df.drop(columns=['TripID'], inplace=True)

In [12]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6.0,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,1,04/11/17 14:53,04/11/17 15:19,1.0,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1.0,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,2,05/07/17 13:17,05/07/17 13:48,1.0,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1.0,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22761,1,05/15/2017 8:00:12 AM,05/15/2017 8:03:23 AM,-2.0,0.70,1,N,48,230,1,4.5,0.0,0.5,1.05,0.0,0.3,6.35
22815,2,03/04/17 23:37,03/04/17 23:51,1.0,1.44,1,N,164,230,1,10.5,0.5,0.5,0.00,0.0,0.3,11.80
22818,2,09/28/2017 11:36:30 AM,09/28/2017 11:49:58 AM,5.0,1.93,1,N,142,238,1,10.5,0.0,0.5,2.82,0.0,0.3,14.12
22881,2,07/28/2017 7:12:44 AM,07/28/2017 7:31:39 AM,2.0,2.01,1,N,229,142,1,13.5,0.0,0.5,2.14,0.0,0.3,21.39
22894,1,06/29/2017 7:30:30 PM,06/29/2017 7:43:29 PM,1.0,0.00,1,N,79,148,3,8.5,1.0,0.5,0.00,0.0,0.3,10.30

In [13]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].map({'Y':1, 'N':0})

IDENTIFYING ENCODED VALUES

In [14]:
categorical_cols = [
    'VendorID',
    'RatecodeID',
    'payment_type',
    'store_and_fwd_flag'
]

for col in categorical_cols:
    print(f"\nColumn: {col}")
    print("Unique Values:", df[col].unique())
    print("Count:", df[col].nunique())
    print("Value Counts:\n", df[col].value_counts())

Column: VendorID
Unique Values: [2 1]
Count: 2
Value Counts:
 VendorID
2    12631
1    10076
Name: count, dtype: int64

Column: RatecodeID
Unique Values: [ 1  2  5  3  4 99]
Count: 6
Value Counts:
 RatecodeID
1     22078
2       513
5        68
3        39
4         8
99        1
Name: count, dtype: int64

Column: payment_type
Unique Values: [1 2 3 4]
Count: 4
Value Counts:
 payment_type
1    15271
2     7268
3      122
4       46
Name: count, dtype: int64

Column: store_and_fwd_flag
Unique Values: [ 0. nan  1.]
Count: 2
Value Counts:
 store_and_fwd_flag
0.0    22409
1.0       99
Name: count, dtype: int64

Categorical Column Descriptions (NYC TLC)
VendorID
1 → Creative Mobile Technologies (CMT) 2 → VeriFone Inc.

payment_type
1 → Credit Card 2 → Cash 3 → No Charge 4 → Dispute 5 → Unknown 6 → Voided Trip

RatecodeID
1 → Standard Rate 2 → JFK 3 → Newark 4 → Nassau/Westchester 5 → Negotiated Fare 6 → Group Ride

store_and_fwd_flag
Y → Stored and Forwarded N → Sent Directly

In [15]:
df['PULocationID'].nunique()

152

In [16]:
df['DOLocationID'].nunique()

216

In [17]:
df['PULocationID'].value_counts()

PULocationID
237    890
161    862
186    792
236    785
162    779
      ...
133      1
78       1
94       1
216      1
55       1
Name: count, Length: 152, dtype: int64

In [18]:
import pandas as pd
zone_df = pd.read_csv("taxi_zone_lookup.csv")
zone_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [19]:
zone_df

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                      NaN          NaN
264         265            NaN           Outside of NYC          NaN

[265 rows x 4 columns]

In [20]:
df = df.merge(
    zone_df[['LocationID', 'Borough']],
    left_on='PULocationID',
    right_on='LocationID',
    how='left'
)

df.rename(columns={'Borough': 'PU_Borough'}, inplace=True)

df.drop('LocationID', axis=1, inplace=True)

In [21]:
df = df.merge(
    zone_df[['LocationID', 'Borough']],
    left_on='DOLocationID',
    right_on='LocationID',
    how='left'
)

df.rename(columns={'Borough': 'DO_Borough'}, inplace=True)

df.drop('LocationID', axis=1, inplace=True)

In [22]:
df[['DOLocationID','DO_Borough']].head()

   DOLocationID DO_Borough
0           231  Manhattan
1            43  Manhattan
2           236  Manhattan
3            97   Brooklyn
4           112   Brooklyn

In [23]:
df[['PULocationID','PU_Borough']].head(100)

    PULocationID PU_Borough
0            100  Manhattan
1            186  Manhattan
2            262  Manhattan
3            188   Brooklyn
4              4  Manhattan
..           ...        ...
95           186  Manhattan
96           163  Manhattan
97           161  Manhattan
98           230  Manhattan
99           113  Manhattan

[100 rows x 2 columns]

In [24]:
print("Pickup Boroughs:", df['PU_Borough'].unique())
print("Dropoff Boroughs:", df['DO_Borough'].unique())

Pickup Boroughs: ['Manhattan' 'Brooklyn' 'Queens' 'Unknown' 'Bronx' nan 'EWR'
 'Staten Island']
Dropoff Boroughs: ['Manhattan' 'Brooklyn' 'Bronx' 'Queens' nan 'Staten Island' 'EWR'
 'Unknown']

In [25]:
df.drop(['PULocationID', 'DOLocationID'], axis=1, inplace=True)

In [26]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,PU_Borough,DO_Borough
0,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6.0,3.34,1,0.0,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56,Manhattan,Manhattan
1,1,04/11/17 14:53,04/11/17 15:19,1.0,1.80,1,0.0,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80,Manhattan,Manhattan
2,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1.0,1.00,1,0.0,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75,Manhattan,Manhattan
3,2,05/07/17 13:17,05/07/17 13:48,1.0,3.70,1,0.0,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69,Brooklyn,Brooklyn
4,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1.0,4.37,1,0.0,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80,Manhattan,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22702,1,05/15/2017 8:00:12 AM,05/15/2017 8:03:23 AM,-2.0,0.70,1,0.0,1,4.5,0.0,0.5,1.05,0.0,0.3,6.35,Manhattan,Manhattan
22703,2,03/04/17 23:37,03/04/17 23:51,1.0,1.44,1,0.0,1,10.5,0.5,0.5,0.00,0.0,0.3,11.80,Manhattan,Manhattan
22704,2,09/28/2017 11:36:30 AM,09/28/2017 11:49:58 AM,5.0,1.93,1,0.0,1,10.5,0.0,0.5,2.82,0.0,0.3,14.12,Manhattan,Manhattan
22705,2,07/28/2017 7:12:44 AM,07/28/2017 7:31:39 AM,2.0,2.01,1,0.0,1,13.5,0.0,0.5,2.14,0.0,0.3,21.39,Manhattan,Manhattan
22706,1,06/29/2017 7:30:30 PM,06/29/2017 7:43:29 PM,1.0,0.00,1,0.0,3,8.5,1.0,0.5,0.00,0.0,0.3,10.30,Manhattan,Manhattan

IDENTIFYING NEGATIVE VALUES

In [27]:
numeric_cols = df.select_dtypes(include=['int64','float64']).columns

for col in numeric_cols:
    print(col, "Negative values:", (df[col] < 0).sum())

VendorID Negative values: 0
passenger_count Negative values: 30
trip_distance Negative values: 0
RatecodeID Negative values: 0
store_and_fwd_flag Negative values: 0
payment_type Negative values: 0
fare_amount Negative values: 13
extra Negative values: 9
mta_tax Negative values: 13
tip_amount Negative values: 0
tolls_amount Negative values: 0
improvement_surcharge Negative values: 14
total_amount Negative values: 14

In [28]:
df = df[df['fare_amount'] > 0]

In [29]:
df = df[df['trip_distance'] > 0]

In [30]:
df = df[df['passenger_count'] > 0]

FIXING DATE TO TIME FORMAT CORRECTLY

In [31]:
for col in ['tpep_pickup_datetime', 'tpep_dropoff_datetime']:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace('\xa0', '', regex=False)
        .str.strip()
    )

In [32]:
df['tpep_pickup_datetime'] = pd.to_datetime(
    df['tpep_pickup_datetime'],
    format='mixed',
    errors='coerce'
)

df['tpep_dropoff_datetime'] = pd.to_datetime(
    df['tpep_dropoff_datetime'],
    format='mixed',
    errors='coerce'
)

In [33]:
print("Pickup nulls:", df['tpep_pickup_datetime'].isna().sum())
print("Dropoff nulls:", df['tpep_dropoff_datetime'].isna().sum())

Pickup nulls: 0
Dropoff nulls: 0

In [34]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag              float64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
PU_Borough                       object
DO_Borough                       object
dtype: object

In [35]:
df.isnull().sum()

VendorID                   0
tpep_pickup_datetime       0
tpep_dropoff_datetime      0
passenger_count            0
trip_distance              0
RatecodeID                 0
store_and_fwd_flag       197
payment_type               0
fare_amount                0
extra                      0
mta_tax                    0
tip_amount                 0
tolls_amount               0
improvement_surcharge      0
total_amount               0
PU_Borough                 7
DO_Borough                53
dtype: int64

In [36]:
df['store_and_fwd_flag'].fillna('N', inplace=True)

/tmp/ipykernel_3894/171426542.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'N' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['store_and_fwd_flag'].fillna('N', inplace=True)

In [37]:
df['PU_Borough'].fillna('Unknown', inplace=True)
df['DO_Borough'].fillna('Unknown', inplace=True)

In [38]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
PU_Borough               0
DO_Borough               0
dtype: int64

In [39]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,PU_Borough,DO_Borough
0,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6.0,3.34,1,0.0,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56,Manhattan,Manhattan
1,1,2017-04-11 14:53:00,2017-04-11 15:19:00,1.0,1.80,1,0.0,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80,Manhattan,Manhattan
2,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1.0,1.00,1,0.0,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75,Manhattan,Manhattan
3,2,2017-05-07 13:17:00,2017-05-07 13:48:00,1.0,3.70,1,0.0,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69,Brooklyn,Brooklyn
4,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1.0,4.37,1,0.0,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80,Manhattan,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22700,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1.0,2.79,1,N,2,13.5,0.0,0.5,0.00,0.0,0.3,14.30,Queens,Queens
22701,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3.0,1.15,1,0.0,1,7.0,0.5,0.5,1.66,0.0,0.3,9.96,Manhattan,Manhattan
22703,2,2017-03-04 23:37:00,2017-03-04 23:51:00,1.0,1.44,1,0.0,1,10.5,0.5,0.5,0.00,0.0,0.3,11.80,Manhattan,Manhattan
22704,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5.0,1.93,1,0.0,1,10.5,0.0,0.5,2.82,0.0,0.3,14.12,Manhattan,Manhattan
22705,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2.0,2.01,1,0.0,1,13.5,0.0,0.5,2.14,0.0,0.3,21.39,Manhattan,Manhattan

Feature Engineering

In [40]:
df['trip_duration'] = (
    df['tpep_dropoff_datetime'] -
    df['tpep_pickup_datetime']
).dt.total_seconds()

In [41]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,PU_Borough,DO_Borough,trip_duration
0,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6.0,3.34,1,0.0,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56,Manhattan,Manhattan,844.0
1,1,2017-04-11 14:53:00,2017-04-11 15:19:00,1.0,1.80,1,0.0,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80,Manhattan,Manhattan,1560.0
2,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1.0,1.00,1,0.0,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75,Manhattan,Manhattan,432.0
3,2,2017-05-07 13:17:00,2017-05-07 13:48:00,1.0,3.70,1,0.0,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69,Brooklyn,Brooklyn,1860.0
4,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1.0,4.37,1,0.0,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80,Manhattan,Brooklyn,1003.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22700,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1.0,2.79,1,N,2,13.5,0.0,0.5,0.00,0.0,0.3,14.30,Queens,Queens,1071.0
22701,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3.0,1.15,1,0.0,1,7.0,0.5,0.5,1.66,0.0,0.3,9.96,Manhattan,Manhattan,493.0
22703,2,2017-03-04 23:37:00,2017-03-04 23:51:00,1.0,1.44,1,0.0,1,10.5,0.5,0.5,0.00,0.0,0.3,11.80,Manhattan,Manhattan,840.0
22704,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5.0,1.93,1,0.0,1,10.5,0.0,0.5,2.82,0.0,0.3,14.12,Manhattan,Manhattan,808.0
22705,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2.0,2.01,1,0.0,1,13.5,0.0,0.5,2.14,0.0,0.3,21.39,Manhattan,Manhattan,1135.0

In [42]:
df['trip_duration'].describe()

count    22482.000000
mean      1023.844009
std       3695.581813
min      -1020.000000
25%        413.000000
50%        664.000000
75%       1103.000000
max      86400.000000
Name: trip_duration, dtype: float64

In [43]:
df[df['trip_duration'] < 0][
    ['tpep_pickup_datetime','tpep_dropoff_datetime','trip_duration']
].head()

     tpep_pickup_datetime tpep_dropoff_datetime  trip_duration
9356  2017-11-05 01:23:00   2017-11-05 01:06:00        -1020.0

In [44]:
(df['trip_duration'] < 0).sum()

1

In [45]:
df = df[df['trip_duration'] >= 0]

In [46]:
df['trip_duration'].describe()

count    22481.000000
mean      1023.934923
std       3695.638868
min          0.000000
25%        413.000000
50%        664.000000
75%       1103.000000
max      86400.000000
Name: trip_duration, dtype: float64

In [47]:
df['pickup_hour'] = df['tpep_pickup_datetime'].dt.hour
df['pickup_weekday'] = df['tpep_pickup_datetime'].dt.weekday
df['pickup_month'] = df['tpep_pickup_datetime'].dt.month
df['pickup_day'] = df['tpep_pickup_datetime'].dt.day

/tmp/ipykernel_3894/2675958914.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pickup_hour'] = df['tpep_pickup_datetime'].dt.hour
/tmp/ipykernel_3894/2675958914.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pickup_weekday'] = df['tpep_pickup_datetime'].dt.weekday
/tmp/ipykernel_3894/2675958914.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pickup_month'] = df['tpep_pickup_datetime'].dt.month
/tmp/ipykernel_3894/2675958914.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pickup_day'] = df['tpep_pickup_datetime'].dt.day

In [48]:
df['is_weekend'] = df['pickup_weekday'].isin([5,6]).astype(int)

/tmp/ipykernel_3894/273218658.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_weekend'] = df['pickup_weekday'].isin([5,6]).astype(int)

In [49]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag               object
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
PU_Borough                       object
DO_Borough                       object
trip_duration                   float64
pickup_hour                       int32
pickup_weekday                    int32
pickup_month                      int32
pickup_day                        int32
is_weekend                        int64
dtype: object

In [50]:
df['store_and_fwd_flag']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
22700      N
22701    0.0
22703    0.0
22704    0.0
22705    0.0
Name: store_and_fwd_flag, Length: 22481, dtype: object

In [51]:
df['passenger_count'].unique()

array([6., 1., 2., 4., 5., 3.])

In [52]:
(df['passenger_count'] % 1 != 0).sum()

0

In [53]:
df['passenger_count'] = df['passenger_count'].astype(int)

/tmp/ipykernel_3894/3052436619.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['passenger_count'] = df['passenger_count'].astype(int)

In [54]:
df['VendorID'] = df['VendorID'].astype('category')
df['RatecodeID'] = df['RatecodeID'].astype('category')
df['payment_type'] = df['payment_type'].astype('category')

/tmp/ipykernel_3894/306009308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['VendorID'] = df['VendorID'].astype('category')
/tmp/ipykernel_3894/306009308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RatecodeID'] = df['RatecodeID'].astype('category')
/tmp/ipykernel_3894/306009308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_type'] = df['payment_type'].astype('category')

In [55]:
df.dtypes

VendorID                       category
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   int64
trip_distance                   float64
RatecodeID                     category
store_and_fwd_flag               object
payment_type                   category
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
PU_Borough                       object
DO_Borough                       object
trip_duration                   float64
pickup_hour                       int32
pickup_weekday                    int32
pickup_month                      int32
pickup_day                        int32
is_weekend                        int64
dtype: object

In [56]:
df['store_and_fwd_flag']

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
22700      N
22701    0.0
22703    0.0
22704    0.0
22705    0.0
Name: store_and_fwd_flag, Length: 22481, dtype: object

In [57]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].astype(str)

/tmp/ipykernel_3894/2558711499.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['store_and_fwd_flag'] = df['store_and_fwd_flag'].astype(str)

In [58]:
df['store_and_fwd_flag'].unique()

array(['0.0', 'N', '1.0'], dtype=object)

In [59]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].replace({
    '0.0': 'N',
    '1.0': 'Y'
})

/tmp/ipykernel_3894/416547335.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['store_and_fwd_flag'] = df['store_and_fwd_flag'].replace({

In [60]:
df['store_and_fwd_flag'].unique()

array(['N', 'Y'], dtype=object)

In [61]:
df['store_and_fwd_flag'] = df['store_and_fwd_flag'].map({'N':0, 'Y':1})

/tmp/ipykernel_3894/2761420862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['store_and_fwd_flag'] = df['store_and_fwd_flag'].map({'N':0, 'Y':1})

In [62]:
df['store_and_fwd_flag'].unique()

array([0, 1])

In [63]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,...,improvement_surcharge,total_amount,PU_Borough,DO_Borough,trip_duration,pickup_hour,pickup_weekday,pickup_month,pickup_day,is_weekend
0,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6,3.34,1,0,1,13.0,0.0,...,0.3,16.56,Manhattan,Manhattan,844.0,8,5,3,25,1
1,1,2017-04-11 14:53:00,2017-04-11 15:19:00,1,1.80,1,0,1,16.0,0.0,...,0.3,20.80,Manhattan,Manhattan,1560.0,14,1,4,11,0
2,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1,1.00,1,0,1,6.5,0.0,...,0.3,8.75,Manhattan,Manhattan,432.0,7,4,12,15,0
3,2,2017-05-07 13:17:00,2017-05-07 13:48:00,1,3.70,1,0,1,20.5,0.0,...,0.3,27.69,Brooklyn,Brooklyn,1860.0,13,6,5,7,1
4,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1,4.37,1,0,2,16.5,0.5,...,0.3,17.80,Manhattan,Brooklyn,1003.0,23,5,4,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22700,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1,2.79,1,0,2,13.5,0.0,...,0.3,14.30,Queens,Queens,1071.0,10,2,5,24,0
22701,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3,1.15,1,0,1,7.0,0.5,...,0.3,9.96,Manhattan,Manhattan,493.0,20,2,8,16,0
22703,2,2017-03-04 23:37:00,2017-03-04 23:51:00,1,1.44,1,0,1,10.5,0.5,...,0.3,11.80,Manhattan,Manhattan,840.0,23,5,3,4,1
22704,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5,1.93,1,0,1,10.5,0.0,...,0.3,14.12,Manhattan,Manhattan,808.0,11,3,9,28,0
22705,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2,2.01,1,0,1,13.5,0.0,...,0.3,21.39,Manhattan,Manhattan,1135.0,7,4,7,28,0

In [64]:
df['store_and_fwd_flag'].value_counts()

store_and_fwd_flag
0    22383
1       98
Name: count, dtype: int64

CAPLING OUTLIERS BASED ON PERCENTAGE

In [65]:
def outlier_percentage(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = data[(data[column] < lower) | (data[column] > upper)]
    
    percentage = (len(outliers) / len(data)) * 100
    
    print(f"{column}")
    print("Outliers:", len(outliers))
    print("Percentage:", round(percentage, 2), "%")
    print("-----------")
    
    return percentage

In [66]:
cols = ['trip_duration','trip_distance','fare_amount','total_amount','tip_amount']

for col in cols:
    outlier_percentage(df, col)

trip_duration
Outliers: 1264
Percentage: 5.62 %
-----------
trip_distance
Outliers: 2522
Percentage: 11.22 %
-----------
fare_amount
Outliers: 2011
Percentage: 8.95 %
-----------
total_amount
Outliers: 2113
Percentage: 9.4 %
-----------
tip_amount
Outliers: 1160
Percentage: 5.16 %
-----------

In [87]:
cols = ['trip_duration','trip_distance','fare_amount','total_amount','tip_amount']

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    df[col] = df[col].clip(lower, upper)

/tmp/ipykernel_3589/109563150.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)
/tmp/ipykernel_3589/109563150.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)
/tmp/ipykernel_3589/109563150.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)
/tmp/ipykernel_3589/109563150.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)
/tmp/ipykernel_3589/109563150.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].clip(lower, upper)

In [89]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,extra,...,improvement_surcharge,total_amount,PU_Borough,DO_Borough,trip_duration,pickup_hour,pickup_weekday,pickup_month,pickup_day,is_weekend
0,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6,3.34,1,0,1,13.0,0.0,...,0.3,16.56,Manhattan,Manhattan,844.0,8,5,3,25,1
1,1,2017-04-11 14:53:00,2017-04-11 15:19:00,1,1.80,1,0,1,16.0,0.0,...,0.3,20.80,Manhattan,Manhattan,1560.0,14,1,4,11,0
2,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1,1.00,1,0,1,6.5,0.0,...,0.3,8.75,Manhattan,Manhattan,432.0,7,4,12,15,0
3,2,2017-05-07 13:17:00,2017-05-07 13:48:00,1,3.70,1,0,1,20.5,0.0,...,0.3,27.69,Brooklyn,Brooklyn,1860.0,13,6,5,7,1
4,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1,4.37,1,0,2,16.5,0.5,...,0.3,17.80,Manhattan,Brooklyn,1003.0,23,5,4,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22700,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1,2.79,1,0,2,13.5,0.0,...,0.3,14.30,Queens,Queens,1071.0,10,2,5,24,0
22701,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3,1.15,1,0,1,7.0,0.5,...,0.3,9.96,Manhattan,Manhattan,493.0,20,2,8,16,0
22703,2,2017-03-04 23:37:00,2017-03-04 23:51:00,1,1.44,1,0,1,10.5,0.5,...,0.3,11.80,Manhattan,Manhattan,840.0,23,5,3,4,1
22704,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5,1.93,1,0,1,10.5,0.0,...,0.3,14.12,Manhattan,Manhattan,808.0,11,3,9,28,0
22705,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2,2.01,1,0,1,13.5,0.0,...,0.3,21.39,Manhattan,Manhattan,1135.0,7,4,7,28,0

FINAL CHECK

In [93]:
print("Final Shape:", df.shape)
print("\nMissing Values:\n", df.isnull().sum())
print("\nSummary:\n", df.describe())

Final Shape: (22481, 23)
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

Missing Values:
 VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
PU_Borough               0
DO_Borough               0
trip_duration            0
pickup_hour              0
pickup_weekday           0
pickup_month             0
pickup_day               0
is_weekend               0
dtype: int64

Summary:
                 tpep_pickup_datetime          tpep_dropoff_datetime  \
count                          22481                          22481
mean   2017-06-29 02:30:09.556158464  2017-06-29 02:47:13.491081216
min              2017-01-01 00:08:00            2017-01-01 00:17:00
25%              2017-03-29 23:15:11            2017-03-29 23:27:12
50%              2017-06-23 08:30:52            2017-06-23 08:34:32
75%              2017-10-01 15:05:00            2017-10-01 15:36:00
max              2017-12-31 23:45:30            2017-12-31 23:49:24
std                              NaN                            NaN

       passenger_count  trip_distance  store_and_fwd_flag   fare_amount  \
count     22481.000000   22481.000000        22481.000000  22481.000000
mean          1.634536       2.341113            0.004359     11.591856
min           1.000000       0.010000            0.000000      0.010000
25%           1.000000       1.000000            0.000000      6.500000
50%           1.000000       1.640000            0.000000      9.500000
75%           2.000000       3.100000            0.000000     14.500000
max           6.000000       6.250000            1.000000     26.500000
std           1.277288       1.833174            0.065882      6.688078

              extra       mta_tax    tip_amount  tolls_amount  \
count  22481.000000  22481.000000  22481.000000  22481.000000
mean       0.333660      0.498643      1.637709      0.309281
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.500000      0.000000      0.000000
50%        0.000000      0.500000      1.360000      0.000000
75%        0.500000      0.500000      2.450000      0.000000
max        4.500000      0.500000      6.125000     19.100000
std        0.461012      0.026010      1.724150      1.385440

       improvement_surcharge  total_amount  trip_duration   pickup_hour  \
count           2.248100e+04  22481.000000   22481.000000  22481.000000
mean            3.000000e-01     14.376442     823.897158     13.728393
min             3.000000e-01      3.300000       0.000000      0.000000
25%             3.000000e-01      8.750000     413.000000      9.000000
50%             3.000000e-01     11.800000     664.000000     14.000000
75%             3.000000e-01     17.800000    1103.000000     19.000000
max             3.000000e-01     31.375000    2138.000000     23.000000
std             1.169646e-13      7.731294     549.851203      6.221524

       pickup_weekday  pickup_month    pickup_day    is_weekend
count    22481.000000  22481.000000  22481.000000  22481.000000
mean         3.025577      6.415328     15.603665      0.280726
min          0.000000      1.000000      1.000000      0.000000
25%          1.000000      3.000000      8.000000      0.000000
50%          3.000000      6.000000     16.000000      0.000000
75%          5.000000     10.000000     23.000000      1.000000
max          6.000000     12.000000     31.000000      1.000000
std          1.951438      3.461732      8.715488      0.449364